services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: supermarket
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  application:
    image: danilo/springboot-architeture-hexagonal:0.0.1
    container_name: jdk
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_data: {}